<h1>190301 Just do! Coding!</h1>

- 오늘 한 것.
  - Asynchronous Call 강의
  - TestBuilder 완료

1. Asynchronous Call 강의
- 비동기 함수
- 어떤 상황, 이벤트, 사건이 발생하면 실행되는 함수다.
- CallBack 함수 - 인자로 사용되는 함수, 인자로 사용할 땐 'something()' 이렇게 사용하지 않게 주의하면서 사용해야한다. '()'없이 'something'만 사용해야함.

2. TestBuilder
드디어 완료했다. 하긴했는데 석연치 않다. 이유는 지금까지 step3을 통과를 못하고 있는 상황이었다. 코드를 잘못 작성해서 그런가 하고 계속 통과될 때까지 수정했다. 계속 수정하고 확인을 반복하다가 통과가 계속 되질 않길래 전에  step4까지 통과됐던 파일을 console창에서 확인해 봤는데 여전히 통과가 되었었다. 혹시나 하는 마음에 step4부분을 주석처리하고 step3까지 통과되나 봤더니 이것도 통과가 되질 않았다. 다시 step4를 포함하니깐 통과가 됐다. 뭔가 이상했다.<br> 
한번 더 해보자 생각하고 맨 처음부터 코드스테이츠 github에서 fork하고 clone까지 하고 코드를 작성했다. step3까지 작성하고 console창에서 확인해봤다. 여전히 통과는 안 됐다. 코드는 고치지 않고 step4까지 작성하고 console창에서 확인해 보니 통과가 됐다. 통과가 됐다. 통과가 되서 좋긴한데 step4까지 작성하고 확인해도 통과했다는 표시가 안떠야 하는거 아닌가? 아니면 '이부분은 통과가 됐는데 아직 step3이 통과가 되질 않았다.' 라는 문구가 나와야 하지 않나.<br>
통과되고 석연치 않은 부분이 이거다. 확실히 통과가 됐다고 안나오니 내가 제대로 과제를 수행했는지 아닌지를 확인할 길이 없다. 그래도 step4까지 작성하고 통과된거 보면 틀리지 않게 작성한 거 같다. 여러번 작성했었지만 코드를 계속쓰면서 수련했다고 생각해야겠다.